
Vagrant.configure("2") do |config|

  config.vm.box = "ubuntu/artful64"
  config.vm.hostname = "block1"
  
  config.vm.network "private_network", ip: "172.22.6.41"

  config.vm.provider "virtualbox" do |vb|
    vb.gui = false  
    vb.memory = "8192"
  end

  config.vm.provision "shell", path: "provision.sh"
  #config.vm.provision "shell", path: "compute-provision.sh"
end
