
Vagrant.configure("2") do |config|

  config.vm.box = "centos/7"
  config.vm.hostname = "packstack"
  #config.ssh.username = "stack"
  
  config.vm.network "private_network", ip: "192.168.0.11"

  config.vm.provider "virtualbox" do |vb|
    vb.gui = false  
    vb.memory = "8192"
  end

  config.vm.provision "shell", path: "provision.sh"
end
