
Vagrant.configure("2") do |config|

  config.vm.box = "artful64-apted"
  config.vm.hostname = "neutron"

  config.vm.network "private_network", ip: "172.22.6.85"
  config.vm.network "private_network", ip: "10.0.0.1", virtualbox__intnet: "tunnel"
  config.vm.provider "virtualbox" do |vb|
    vb.gui = false  
    vb.memory = "2048"
  end

  config.vm.provision "shell", path: "neutron-provision.sh"
end
