
Vagrant.configure("2") do |config|

  config.vm.box = "artful64-apted"
  config.vm.hostname = "compute1"

  config.vm.network "private_network", ip: "172.22.6.31"

  config.vm.provider "virtualbox" do |vb|
    vb.gui = false  
    vb.memory = "8192"
  end

  config.vm.provision "shell", path: "compute-provision.sh"
end
