
Vagrant.configure("2") do |config|

  config.vm.box = "ubuntu/artful64"
  config.vm.hostname = "controller"
  
  config.vm.network "private_network", ip: "172.22.6.95"

  config.vm.provider "virtualbox" do |vb|
    vb.gui = false  
    vb.memory = "4096"
  end

  config.vm.provision "shell", path: "controller-provision.sh"
end
